#!/bin/bash

(git status --porcelain | awk '{print $2}' | xargs ag -l --ignore ./**/*.go --ignore ./src '#!/bin' | xargs shellcheck > /dev/null 2>&1)
if [ $? -ne 0 ]; then
  printf '\nWARNING: Shellcheck (Shell Script lint tool) detected some potential issues in this commit.'
  printf '\nRun Shellcheck against your script changes to see details.\n\n'
fi
