#!/bin/sh

TEMPLATES=$(dirname $0)/templates

infrastructure=$1

shift

spiff merge \
  $TEMPLATES/riak-cs-service.yml \
  $TEMPLATES/$infrastructure-resource-pools.yml \
  $TEMPLATES/riak-cs-jobs.yml \
  $TEMPLATES/$infrastructure-networks.yml \
  $*
