#!/bin/sh

TEMPLATES=$(dirname $0)/templates

infrastructure=$1

if [ "$infrastructure" != "warden" ] && \
    [ "$infrastructure" != "vsphere" ] && \
    [ "$infrastructure" != "aws" ] && \
    [ "$infrastructure" != "openstack" ]; then
  echo "usage: ./generate_deployment_manifest <warden|vsphere|aws|openstack> [stubs...]"
  exit 1
fi

shift

spiff merge \
  $TEMPLATES/riak-cs-service.yml \
  $TEMPLATES/$infrastructure-resource-pools.yml \
  $TEMPLATES/riak-cs-jobs.yml \
  $TEMPLATES/$infrastructure-networks.yml \
  $TEMPLATES/$infrastructure-properties.yml \
  $*
