#!/bin/bash -x

function has_upstream() {
  git rev-parse @{u} > /dev/null 2>&1
}

$(dirname $0)/scripts/install-git-hooks

has_upstream && git pull

git submodule foreach --recursive git submodule sync && git submodule update --init --recursive

git clean -ffd
