#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )

# Use make-manifest script to handle targetting and logging in to the director
${MY_DIR}/make_manifest

function assert_rebase_attempted_without_changes() {

  if [ -z "$1" ]; then
    echo "no input provided - exiting"
    exit 1
  fi
  rebase_output=$1

  acceptable_search_result='rebase.*attempted.*without.*changes'
  (echo $rebase_output | grep -i $acceptable_search_result) > /dev/null 2>&1
  acceptable_search_result_found=$?

  if [ $acceptable_search_result_found -ne 0 ]; then
    echo "Unnacceptable upload output - failed to upload release - exiting"
    exit 1
  fi
  echo "Acceptable upload output - rebase attempted without changes"
}

pushd ${RELEASE_DIR}
    bosh create release --force --name cf-riak-cs
    upload_output=$(bosh -n upload release --rebase) || assert_rebase_attempted_without_changes "${upload_output}"
popd
