#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )
# And that the release directory lives one directory below the workspace directory.
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

OK_COLOR='\033[1;32m'
ACTION_COLOR='\033[1;33m'
INFO_COLOR='\033[1;36m'
NO_COLOR='\033[0m'

CONFIG_LOCATION=${CONFIG_LOCATION:-${RELEASE_DIR}/integration-config.json}
echo -e "Creating config file at ${INFO_COLOR}${CONFIG_LOCATION}${NO_COLOR}..."

DOMAIN=${DOMAIN:-bosh-lite.com}

cat > ${CONFIG_LOCATION} <<EOF

{
  "api":                 "api.${DOMAIN}",
  "admin_user":          "admin",
  "admin_password":      "admin",
  "apps_domain":         "${DOMAIN}",
  "riak_cs_host":        "p-riakcs.${DOMAIN}",
  "riak_cs_scheme" :     "https://",
  "service_name":        "p-riakcs",
  "plan_name":           "developer",
  "broker_host":         "p-riakcs-broker.${DOMAIN}",
  "timeout_scale":       1.0,
  "skip_ssl_validation": true
}
EOF

echo -e "${OK_COLOR}OK${NO_COLOR}"

echo -e "
TIP: Export the environment variable with the following command:

${ACTION_COLOR}export CONFIG=${CONFIG_LOCATION}${NO_COLOR}"
