#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )

# And that the release directory lives one directory below the workspace directory.
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

OK_COLOR='\033[1;32m'
ACTION_COLOR='\033[1;33m'
INFO_COLOR='\033[1;36m'
NO_COLOR='\033[0m'

mkdir -p ${RELEASE_DIR}/bosh-lite/tmp
mkdir -p ${RELEASE_DIR}/bosh-lite/manifest

cp \
  ${RELEASE_DIR}/bosh-lite/stub.yml \
  ${RELEASE_DIR}/bosh-lite/tmp/cf-riak-cs-stub-with-uuid.yml

DIRECTOR_IP=${DIRECTOR_IP:-192.168.50.4}
API_ADDRESS=${API_ADDRESS:-10.244.0.34}

bosh -n target ${DIRECTOR_IP}
bosh login admin admin
DIRECTOR_UUID=$(bosh status | grep UUID | awk '{print $2}')
echo $DIRECTOR_UUID

perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" bosh-lite/tmp/cf-riak-cs-stub-with-uuid.yml

${RELEASE_DIR}/generate_deployment_manifest \
  warden \
  ${RELEASE_DIR}/bosh-lite/tmp/cf-riak-cs-stub-with-uuid.yml \
  "$@" > ${RELEASE_DIR}/bosh-lite/manifests/cf-riak-cs-manifest.yml

bosh deployment bosh-lite/manifests/cf-riak-cs-manifest.yml
