#!/bin/bash

BOSH_RELEASES_DIR=${BOSH_RELEASES_DIR:-~/workspace}
RIAKCS_RELEASE_DIR=${RIAKCS_RELEASE_DIR:-$BOSH_RELEASES_DIR/cf-riak-cs-release}

if [[ ! -d $RIAKCS_RELEASE_DIR ]]; then
  echo "Cannot find cf-riak-cs-release at $RIAKCS_RELEASE_DIR; override with \$RIAKCS_RELEASE_DIR variable"
  exit 1
fi

cd $RIAKCS_RELEASE_DIR
mkdir -p bosh-lite/tmp
mkdir -p bosh-lite/manifests
cp bosh-lite/stub.yml bosh-lite/tmp/stub-with-uuid.yml
DIRECTOR_UUID=$(bosh status | grep UUID | awk '{print $2}')
echo $DIRECTOR_UUID
perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" bosh-lite/tmp/stub-with-uuid.yml

$RIAKCS_RELEASE_DIR/generate_deployment_manifest warden bosh-lite/tmp/stub-with-uuid.yml > bosh-lite/manifests/cf-riak-cs-manifest.yml
bosh deployment bosh-lite/manifests/cf-riak-cs-manifest.yml

