#!/bin/bash

# Control script to start/stop ruby/rack riak-cs job on a BOSH controlled VM
#
# In local development, this script can be run manually. Examples below assume you are in the root of this release project.
#
# Start process example:
# APP_DIR=/path/to/riak-cs RACK_ENV=development COMMAND=shotgun PORT=9393 jobs/riak-cs/templates/riak-cs_ctl start
#
# View STDOUT/STDERR logs:
# jobs/riak-cs/templates/riak-cs_ctl logs
#
# Clear logs:
# jobs/riak-cs/templates/riak-cs_ctl clearlogs

RUN_DIR=/var/vcap/sys/run/riak-cs
LOG_DIR=/var/vcap/sys/log/riak-cs
STORE=/var/vcap/store/riak-cs
PIDFILE=$RUN_DIR/riak-cs.pid

export PATH=/var/vcap/packages/ruby/bin:$PATH
export HOME=/var/vcap

COMMAND=${COMMAND:-/var/vcap/packages/riak-cs/rel/bin/riak-cs start}
HOME=${HOME:-/home/vcap}

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $STORE

    # Put the config files in place

    cp /var/vcap/jobs/riak-cs/config/riak.app.config /var/vcap/packages/riak/rel/etc/app.config
    cp /var/vcap/jobs/riak-cs /config/riak.vm.args /var/vcap/packages/riak/rel/etc/vm.args

    cp /var/vcap/jobs/riak-cs/config/riak_cs.app.config /var/vcap/packages/riak-cs/rel/etc/app.config
    cp /var/vcap/jobs/riak-cs/config/riak_cs.vm.args /var/vcap/packages/riak-cs/rel/etc/vm.args

    # Set the max open file limit
    ulimit -n 65536

    # Update vm.args with current IP address
    IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
    sed -i "s/127.0.0.1/$IP_ADDR/" /var/vcap/packages/riak/rel/etc/vm.args
    sed -i "s/127.0.0.1/$IP_ADDR/" /var/vcap/packages/riak/rel/etc/app.config

    sed -i "s/127.0.0.1/$IP_ADDR/" /var/vcap/packages/riak-cs/rel/etc/vm.args
    sed -i "s/127.0.0.1/$IP_ADDR/" /var/vcap/packages/riak-cs/rel/etc/app.config

<% if properties.riak.firewall_enabled %>
    bash /var/vcap/jobs/riak-cs/restrict_riak_requests_to_cluster_ip_range.sh
<% end %>

    # Start riak
    /var/vcap/packages/riak/rel/bin/riak start

    # Join the cluster if we arn't the seed node
    if [ "$IP_ADDR" != "<%= properties.riak.seed_node %>" ]
    then
     bash /var/vcap/jobs/riak-cs/join_cluster.sh
    fi

    # Create admin user for service broker
    if [ "$IP_ADDR" != "<%= properties.riak.seed_node %>" ]
    then
      /var/vcap/packages/erlang/bin/escript /var/vcap/jobs/riak-cs/bin/create_cs_user.escript
    fi

    # Start riak-cs
    /var/vcap/packages/riak-cs/rel/bin/riak-cs start
    pgrep -f 'beam.*riak-cs' > $PIDFILE
    ;;

  stop)
    /var/vcap/packages/riak-cs/rel/bin/riak-cs stop
    /var/vcap/packages/riak/rel/bin/riak stop
    rm -f $PIDFILE
    ;;

  logs)
    cat $LOG_DIR/*
    ;;

  tail)
    tail -f $LOG_DIR/*
    ;;

  clearlogs)
    rm $LOG_DIR/*
    ;;

  *)
  echo "Usage: riak-cs_ctl {start|stop|logs|tail|clearlogs}" ;;
esac
exit 0
