#!/bin/bash

# Control script to start/stop ruby/rack riak-cs job on a BOSH controlled VM
#
# In local development, this script can be run manually. Examples below assume you are in the root of this release project.
#
# Start process example:
# APP_DIR=/path/to/riak-cs RACK_ENV=development COMMAND=shotgun PORT=9393 jobs/riak-cs/templates/riak-cs_ctl start
#
# View STDOUT/STDERR logs:
# jobs/riak-cs/templates/riak-cs_ctl logs
#
# Clear logs:
# jobs/riak-cs/templates/riak-cs_ctl clearlogs

RUN_DIR=/var/vcap/sys/run/riak-cs
LOG_DIR=/var/vcap/sys/log/riak-cs
STORE=/var/vcap/store/riak-cs
PIDFILE=$RUN_DIR/riak-cs.pid

export PATH=/var/vcap/packages/ruby/bin:$PATH
export HOME=/var/vcap

COMMAND=${COMMAND:-/var/vcap/packages/riak-cs/rel/bin/riak-cs start}
HOME=${HOME:-/home/vcap}

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $STORE

    # Put the config files in place
    cp /var/vcap/jobs/riak-cs/config/app.config /var/vcap/packages/riak-cs/rel/etc/app.config
    cp /var/vcap/jobs/riak-cs/config/vm.args /var/vcap/packages/riak-cs/rel/etc/vm.args

    # Update vm.args with current IP address
    IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
    sed -i "s/127.0.0.1/$IP_ADDR/" /var/vcap/packages/riak-cs/rel/etc/vm.args
    sed -i "s/127.0.0.1/$IP_ADDR/" /var/vcap/packages/riak-cs/rel/etc/app.config

    # Start riak-cs
    /var/vcap/packages/riak-cs/rel/bin/riak-cs start
    ps -A | grep beam | sed -e 's/^[ \t]*//' | awk '{split($0,a,/ /); print a[1]}' > $PIDFILE
    ;;

  stop)
    /var/vcap/packages/riak-cs/rel/bin/riak-cs stop
    rm -f $PIDFILE
    ;;

  logs)
    cat $LOG_DIR/*
    ;;

  tail)
    tail -f $LOG_DIR/*
    ;;

  clearlogs)
    rm $LOG_DIR/*
    ;;

  *)
  echo "Usage: riak-cs_ctl {start|stop|logs|tail|clearlogs}" ;;
esac
exit 0
