#!/bin/bash

set -ex

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives two directories below the release directory.
RELEASE_DIR="$( cd ${MY_DIR}/../.. && pwd )"
# And that the release directory lives one directory below the workspace directory.
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

${MY_DIR}/with_docker_cleanup docker run --privileged \
  -v ${WORKSPACE_DIR}:/workspace/ \
  -w "/workspace/cf-riak-cs-release" \
  cloudfoundry/cf-riak-cs-ci "$@"
