---
networks: (( merge ))

properties:
  app_domains: (( merge ))
  domain: (( merge ))
  nats:
    user: (( merge ))
    password: (( merge ))
    port: (( merge ))
    machines: (( merge ))
  broker:
    name: p-riakcs
    host: (( .properties.external_broker_host ))
    port: ~
    username: (( merge ))
    password: (( merge ))
  riak_cs:
    admin_key: (( merge ))
    admin_secret: (( merge ))
    port: ~
    register_route: ~
    ssl_enabled: ~
    skip_ssl_validation: ~
    seeded_buckets: ~
  external_broker_host: (( "p-riakcs-broker." .properties.domain ))
  external_riakcs_host: (( "p-riakcs." .properties.domain ))
  cf:
    admin_username: (( merge ))
    admin_password: (( merge ))
    api_url: (( "https://api." .properties.domain ))
    skip_ssl_validation: ~
  acceptance_tests:
    timeout_scale: ~

jobs:
- name: riak-cs
  template: riak-cs
  instances: 3
  resource_pool: riak-pool
  networks:
  - name: riak-cs1
    static_ips: (( static_ips(1, 2, 3) ))
  persistent_disk: 10240
  properties:
    <<: (( merge || nil ))
    stanchion:
      ip: (( jobs.stanchion.networks.riak-cs1.static_ips.[0] ))
    riak:
      network: (( jobs.[0].networks.[0].name ))
      ips: (( jobs.[0].networks.[0].static_ips ))
      seed_node: (( jobs.[0].networks.[0].static_ips.[0] ))
      firewall_enabled: (( merge ))
    riak_cs:
      ips:  (( jobs.[0].networks.[0].static_ips ))
      admin_key: (( .properties.riak_cs.admin_key ))
      admin_secret: (( .properties.riak_cs.admin_secret ))
      seeded_buckets: (( .properties.riak_cs.seeded_buckets ))
      port: (( .properties.riak_cs.port ))
      register_route: (( .properties.riak_cs.register_route ))
      ssl_enabled: (( .properties.riak_cs.ssl_enabled ))
    nats: (( .properties.nats ))
    external_riakcs_host: (( .properties.external_riakcs_host ))
    syslog_aggregator: (( .properties.syslog_aggregator || nil ))

- name: stanchion
  template: stanchion
  instances: 1
  resource_pool: riak-pool
  networks:
  - name: riak-cs1
    static_ips: (( static_ips(0) ))
  persistent_disk: 4096
  properties:
    <<: (( merge || nil ))
    riak:
      seed_node: (( jobs.[0].networks.[0].static_ips.[0] ))
    riak_cs:
      admin_key: (( .properties.riak_cs.admin_key ))
      admin_secret: (( .properties.riak_cs.admin_secret ))

- name: cf-riak-cs-broker
  template: cf-riak-cs-broker
  instances: 1
  resource_pool: broker-pool
  networks:
  - name: riak-cs1
  properties:
    <<: (( merge || nil ))
    broker:
      port: ~
      network: (( jobs.cf-riak-cs-broker.networks.riak-cs1.name ))
      name: (( .properties.broker.name ))
      host: (( .properties.external_broker_host ))
      username: (( .properties.broker.username ))
      password: (( .properties.broker.password ))
    catalog:
      services:
      - bindable: true
        description: An S3-compatible object store based on Riak CS
        id: 33d2eeb0-0236-4c83-b494-da3faeb5b2e8
        metadata:
          displayName: Riak CS for Pivotal Cloud Foundry
          documentationUrl: http://docs.pivotal.io/p-riakcs/
          imageUrl: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAypJREFUeNrsm72O00AQgPes9A68AAeiv0gUdCQCCujMCxA30J3OoqM5OTSUGNFROS9AXNCCEjoKJF/NCUIBJdg9UpgN45PP5//1XtYejzRyoii7O59nZ/9m9zabDaMsA+kVPD+awIPrCHQIOi74ywo0APVBl39fvl7KbN+eDA8Ao014GGi4LlhcyEGAegDDVRYAGL0PDwvUbMDoPBgcggMw1koAAMO5Wzug00vuvnMOHEAEIoVogsbzN77egfEM61xjGy7XA9DdPdADRYL5CY85dbqFVsN4AyO0KsYzbIuPbZMHACqw4bGQGOREhLdpgW1svgtAwe6O+nqtAAndwWzMA1pm/DZAYpvFAaBLtcn4OARbqAtgUFm0fLr/CLqDVxkADnW+ogGv6uxxlDVE5nUBrwPGR6ODVykGYN8pPc4f33/IgDAb37ipKoSDrBmjljG3t1j3xEbbCj3A6Yjrp3UFJxcABr4p665M0cZMD7BY98XKA2ASAGCmAsBtLJ0AAB1tveABBqMjRhqACSEAk3MAcOtaJwRAR5vPPIDS2z/nBRGAEUEAW5ujk6Fh06V/fHrI7lxvZm3w6fspu/v2zfbz/pWr7PGt22z17SvoqUixwziAsSzMvPEikoR4DQAc33vAXsBnQQDjOABpEr25usJXmTJFY8SlB9AD6AH0AHoA7H9aCjVZxQEEBAEEcQA+QQB+HMCSIIDlGQBMRQsJGR9G6Xdakgilt58E4BEC4F0AgEmIIRH3d6MvyeUw/+GoydpkL2driBv/kgTgNAXA//WzufGqwbJY4nxwkHhbPPGQZ2AKnw8+e/9ORfefJxMl0tYCVkdjQchSzj4HKX02wASJV1Vr+PDkUGUAdlpe8SAjcDl4flYqS+THn9/Cm59VhddZQU64TWk/5G2KRimxhSdG8y+ft6qw6xuV9wMwWJgd6PtmXhK1VjCG8xnTrMXGz/JyBLmUyhVuYapsNOQVenCpLTEsaN4140sDiEGYtcTtS8euyjdGMH/YZerlE4QY8CqtaslfmRG6NYbpp/YOvSHEGZ5TtwDy1+b6i5P91VnJt8dJXp5uk/wTYAAYLEbR+lwY3QAAAABJRU5ErkJggg==
          longDescription: Provisioning a service instance creates a Riak CS bucket. Binding applications to the instance creates unique credentials for each application to access the bucket.
          providerDisplayName: Pivotal Software
          supportUrl: https://support.pivotal.io
        name: p-riakcs
        plans:
        - description: Shared Riak CS cluster, private buckets, no storage quota
          id: 946ce484-376b-41b4-8c4e-4bc830676115
          metadata:
            bullets:
            - Not for production use
            - Shared Riak CS cluster
            - Buckets are private
            - No storage quota
            costs:
            - amount:
                usd: 0.0
              unit: MONTH
            displayName: Developer
          name: developer
        tags:
        - riak-cs
        - s3
    riak_cs:
      admin_key: (( .properties.riak_cs.admin_key ))
      admin_secret: (( .properties.riak_cs.admin_secret ))
      ssl_enabled: (( .properties.riak_cs.ssl_enabled ))
      skip_ssl_validation: (( .properties.riak_cs.skip_ssl_validation ))
    external_riakcs_host: (( .properties.external_riakcs_host ))
    external_broker_host: (( .properties.external_broker_host ))
    nats: (( .properties.nats ))
    syslog_aggregator: (( .properties.syslog_aggregator || nil ))

- name: broker-registrar
  lifecycle: errand
  template: broker-registrar
  instances: 1
  resource_pool: broker-pool
  networks:
  - name: riak-cs1
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
      api_url: (( .properties.cf.api_url ))
      skip_ssl_validation: (( .properties.cf.skip_ssl_validation ))
    broker:
      name: (( .properties.broker.name ))
      host: (( .properties.broker.host ))
      port: (( .properties.broker.port ))
      username: (( .properties.broker.username ))
      password: (( .properties.broker.password ))
    riak_cs:
      register_route: (( .properties.riak_cs.register_route ))

- name: broker-deregistrar
  lifecycle: errand
  template: broker-deregistrar
  instances: 1
  resource_pool: broker-pool
  networks:
  - name: riak-cs1
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
      api_url: (( .properties.cf.api_url ))
      skip_ssl_validation: (( .properties.cf.skip_ssl_validation ))
    broker:
      name: (( .properties.broker.name ))
    riak_cs:
      register_route: (( .properties.riak_cs.register_route ))

- name: acceptance-tests
  lifecycle: errand
  template: acceptance-tests
  instances: 1
  resource_pool: broker-pool
  networks:
  - name: riak-cs1
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
      apps_domain: (( .properties.app_domains.[0] ))
      api_url: (( .properties.cf.api_url ))
      skip_ssl_validation: (( .properties.cf.skip_ssl_validation ))
    riak_cs:
      ssl_enabled: (( .properties.riak_cs.ssl_enabled ))
      register_route: (( .properties.riak_cs.register_route ))
    catalog:
      services: (( jobs.cf-riak-cs-broker.properties.catalog.services ))
    broker:
      host: (( .properties.external_broker_host ))
    external_riakcs_host: (( .properties.external_riakcs_host ))
    timeout_scale: (( .properties.acceptance_tests.timeout_scale ))
