#!/bin/bash

# Control script to start/stop ruby/rack riak job on a BOSH controlled VM
#
# In local development, this script can be run manually. Examples below assume you are in the root of this release project.
#
# Start process example:
# APP_DIR=/path/to/riak RACK_ENV=development COMMAND=shotgun PORT=9393 jobs/riak/templates/riak_ctl start
#
# View STDOUT/STDERR logs:
# jobs/riak/templates/riak_ctl logs
#
# Clear logs:
# jobs/riak/templates/riak_ctl clearlogs

# TODO - change "EXECUTABLE_SERVER" to the command to run

RUN_DIR=/var/vcap/sys/run/riak
LOG_DIR=/var/vcap/sys/log/riak
STORE=/var/vcap/store/riak
PIDFILE=$RUN_DIR/riak.pid

export PATH=/var/vcap/packages/ruby/bin:$PATH

COMMAND=${COMMAND:-/var/vcap/packages/riak/bin/riak start}
HOME=${HOME:-/home/vcap}

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $STORE

	cp /var/vcap/jobs/riak/config/app.config /var/vcap/packages/riak/etc/app.config

    /var/vcap/packages/riak/bin/riak start >>$LOG_DIR/riak.stdout.log 2>>$LOG_DIR/riak.stderr.log
    ;;

  stop)
    /var/vcap/packages/riak/bin/riak stop
    ;;

  logs)
    cat $LOG_DIR/*
    ;;

  tail)
    tail -f $LOG_DIR/*
    ;;

  clearlogs)
    rm $LOG_DIR/*
    ;;

  *)
  echo "Usage: riak_ctl {start|stop|logs|tail|clearlogs}" ;;
esac
exit 0
